{% set name = "pydp" %}
{% set version = "0.1.7dev" %}
{% set commit = "1b1dc6639173c0a13613189ec21851604a4c7335" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/OpenMined/PyDP/archive/v{{ version }}.tar.gz
    sha256: 719e5a424bc60862d264ea4e712e9f74699b127b06910be6e6b70b4abd5c4147

  - url: https://github.com/google/differential-privacy/archive/{{ commit }}.tar.gz
    sha256: 03a3c53be6be5dbd05addd2c27ce997aba8635ee89376f7618d01ee628fb6690
    fn: differential-privacy.tar.gz
    folder: third_party/differential-privacy

build:
  number: 0
  skip: True  # [win or py<37]

requirements:
  build:
    - {{ compiler('cxx') }}
    - bazel==2.1.0
  host:
    - python
    - pip
    - pytest
  run:
    - {{ pin_compatible('python', min_pin='3.8') }}
    - pytest

test:
  source_files:
    - tests
  imports:
    - pydp
  commands:
    - python -m pytest tests

about:
  home: https://github.com/OpenMined/PyDP
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: "A python wrapper for https://github.com/google/differential-privacy"
  dev_url: https://github.com/OpenMined/PyDP

extra:
  recipe-maintainers:
    - alejandrosame
